### PR TITLE
Improve Index.of to also accept class files and JAR files

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Any thoughts on a directory with jar files? Easily done by the client, but just for convenience.

**Comment by Ladicek** [comment]
I didn't have a need for that yet :-) The things I'm adding here are things I've frequently used over past months.

**Comment by MikeEdgar** [comment]
Just thinking of the situation "here's my app .jar and here's my lib/*.jar"

**Comment by Ladicek** [comment]
It could be useful, but I think I'll let anyone _who actually has a use for it_ add it :-)

**Pull request merged**
