### PR TITLE
[2.4] Support ClassInfo signature at any position

### LINKED ISSUE #160: Class signature parsing skipped for records
The `Indexer#applySignatures` method requires that the signature for a class be the last entry in the list of signatures. However, with records, the class's signature is followed by the record components' signatures. 

An example record that where generic type information is not included in the index for the class's type parameters.
```java
record MyRecord<T>(T content) {
} 
```

### PR DESCRIPTION
**Pull request by MikeEdgar**
Fixes #160

### CODE REVIEW

**Comment by MikeEdgar** [comment]
CI will fail without `wildfly:typeannotation-test` release including https://github.com/wildfly/typeannotation-test/pull/3

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Looks fine. Do you want to submit a PR against the `smallrye` branch, or should I?

**Comment by Ladicek** [comment]
I submitted a PR to the `smallrye` branch: #163

**Comment by Ladicek** [comment]
I guess you'd like to have 2.4.2 released with this fix soon? :-)

**Comment by MikeEdgar** [comment]
Thanks for handling this and doing the `smallrye` PR. Whenever you get a chance for a release is OK.

**Comment by Ladicek** [comment]
Thank _you_ for submitting the PR! I'm looking into #161 and if there's a realistic chance I'm able to fix it today or tomorrow, I'd rather include it. If not, I'll release 2.4.2 just with this fix -- today or tomorrow at latest. Please shout if that doesn't work for you.

**Comment by Ladicek** [comment]
Jandex 2.4.2.Final is on its way to Central. Jandex Maven plugin will follow tomorrow.

**Comment by Ladicek** [comment]
And Jandex Maven plugin 1.2.2 is out and on its way to Central.

**Pull request merged**
