### PR TITLE
Override equals()/hashCode() in AnnotationValue.BooleanValue

### LINKED ISSUE #81: org.jboss.jandex.AnnotationValue.BooleanValue does not override equals()/hashCode()
As a result, the boolean values is ignored in `equals()`, i.e. it returns always `true` for two boolean annotation values with the same name.

### PR DESCRIPTION
**Pull request by mkouba**
- resolves #81

### CODE REVIEW

**Comment by mkouba** [comment]
CC @n1hility 

Maybe it's a good time to release another bugfix version of jandex too?

**Comment by famod** [comment]
Have you seen https://github.com/wildfly/jandex/issues/81#issuecomment-645210224 ?

**Comment by mkouba** [comment]
@famod Yes, I did. I think that we should keep things simple and use the "specialized" versions of `equals()/hashCode()`. This way we can avoid unnecessary boxing for primitive values and apply specific strategies for `hashCode()`.

**Comment by famod** [comment]
@mkouba Ok, your decision (no offense!).
It's just that the abstract base class provides a `toString()` that is inherently incomplete and AFAICS _no_ subclass should rely on that (but is not foced to implement a complete `toString()`).

**Comment by mkouba** [comment]
> Ok, your decision (no offense!).

It's up to @n1hility. I've only sent a PR ;-).

**Pull request merged**
